version: "3"

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql-quiz
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql

  RemoteCodeCompiler:
    build: ../RemoteCodeCompiler
    image: remodecodecompiler
    container_name: remotecodecompiler
    restart: unless-stopped
    ports:
      - 8080:8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - EXECUTION_MEMORY_MAX=10000
      - EXECUTION_MEMORY_MIN=0
      - EXECUTION_TIME_MAX=60
      - EXECUTION_TIME_MIN=0

volumes:
  mysql-data:
